### ISSUE TITLE
Will you keep the capital M in the import path?

### ISSUE THREAD

**Issue by ghost** [mitranim/repr#1]
This tool looks great! I plan to vendor it. Historically there were a bunch of issues when an import path [changed](https://duckduckgo.com/?q=github+sirupsen+case&t=brave&ia=web) from `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`.

Just wanted to let you know early, in case you ever consider changing to `github.com/mitranim`!

**Comment by mitranim** [comment]
Huh. Interesting question you ask that I've been wondering myself. The capital letter is annoying to type, and inconsistent with the more common convention of lowercase usernames. If changing the case breaks Go imports, maybe do it sooner rather than later. 🤔

**Comment by mitranim** [comment]
Thanks for raising the awareness. I'll have to mull it over for a day or so.

**Comment by mitranim** [comment]
Gonna try it now. Feel free to let me know if anything breaks 😄
